In [ ]:
    - my name is [steav]{"entity": "name", "group": "1"}
    - name is [steav]{"entity": "name", "group": "1"}
    - call my name [steav]{"entity": "name", "group": "1"}
    - i prefer name [steav]{"entity": "name", "group": "1"}
    - i prefer the name [steav]{"entity": "name", "group": "1"}
    - you can call me name [steav]{"entity": "name", "group": "1"}
    - [steav]{"entity": "name", "group": "1"} is the name
    - the name is [steav]{"entity": "name", "group": "1"}
    - you can refer to me as name [steav]{"entity": "name", "group": "1"}
    - i go by the name [steav]{"entity": "name", "group": "1"}
    - the name i go by is [steav]{"entity": "name", "group": "1"}
    - [steav]{"entity": "name", "group": "1"} is what you can call me
    - you may know name as [steav]{"entity": "name", "group": "1"}
    - people call me name [steav]{"entity": "name", "group": "1"}
    - [steav]{"entity": "name", "group": "1"} is the name i use
    - refer to name as [steav]{"entity": "name", "group": "1"}
    - i'm also known as name [steav]{"entity": "name", "group": "1"}
    - my name is [gayan](name)
    - i'm [gayan](name)
    - [gayan](name)
    - call me [gayan](name)
    - i prefer name me [gayan](name)
    - i prefer [gayan](name)
    - you can call me [gayan](name)
    - [gayan](name) is the name
    - the name is [gayan](name)
    - you can refer to me as [gayan](name)
    - i go by the name [gayan](name)
    - the name i go by is [gayan](name)
    - [gayan](name) is what you can call me
    - you may know me as [gayan](name)
    - people call me [gayan](name)
    - [gayan](name) is the name i use
    - refer to me as [gayan](name)
    - i'm also known as [gayan](name)
    - my name is [kasun](name)
    - i'm [kasun](name)
    - [kasun](name)
    - call me [kasun](name)
    - i prefer name me [kasun](name)
    - i prefer [kasun](name)
    - you can call me [kasun](name)
    - [kasun](name) is the name
    - the name is [kasun](name)
    - you can refer to me as [kasun](name)
    - i go by the name [kasun](name)
    - the name i go by is [kasun](name)
    - [kasun](name) is what you can call me
    - you may know me as [kasun](name)
    - people call me [kasun](name)
    - [kasun](name) is the name i use
    - refer to me as [kasun](name)
    - i'm also known as [kasun](name)
    - my name is [tharidu](name)
    - i'm [tharidu](name)
    - [tharidu](name)
    - call me [tharidu](name)
    - i prefer name me [tharidu](name)
    - i prefer [tharidu](name)
    - you can call me [tharidu](name)
    - [tharidu](name) is the name
    - the name is [tharidu](name)
    - you can refer to me as [tharidu](name)
    - i go by the name [tharidu](name)
    - the name i go by is [tharidu](name)
    - [tharidu](name) is what you can call me
    - you may know me as [tharidu](name)
    - people call me [tharidu](name)
    - [tharidu](name) is the name i use
    - refer to me as [tharidu](name)
    - i'm also known as [tharidu](name)
    - my name is [amal](name)
    - i'm [amal](name)
    - [amal](name)
    - call me [amal](name)
    - i prefer name me [amal](name)
    - i prefer [amal](name)
    - you can call me [amal](name)
    - [amal](name) is the name
    - the name is [amal](name)
    - you can refer to me as [amal](name)
    - i go by the name [amal](name)
    - the name i go by is [amal](name)
    - [amal](name) is what you can call me
    - you may know me as [amal](name)
    - people call me [amal](name)
    - [amal](name) is the name i use
    - refer to me as [amal](name)
    - i'm also known as [amal](name)

In [1]:
pip install pyresparser

Requirement already satisfied: pyresparser in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (1.0.6)
Requirement already satisfied: attrs>=19.1.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (22.1.0)
Requirement already satisfied: blis>=0.2.4 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (0.7.11)
Requirement already satisfied: certifi>=2019.6.16 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (2023.7.22)
Requirement already satisfied: chardet>=3.0.4 in c:\users\sheha\appdata\roaming\python\python310\site-packages (from pyresparser) (4.0.0)
Requirement already satisfied: cymem>=2.0.2 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (2.0.8)
Requirement already satisfied: docx2txt>=0.7 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (0.8)
Requirement already satisfied: idna>=2.8 in c:\users\sheha\appdata\roaming\python\python310\site-packages (from pyresparser) (2.10)
Requirement already satisfied: jsonschema>=3.0.1 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (4.17.3)
Requirement already satisfied: nltk>=3.4.3 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (3.8.1)
Requirement already satisfied: numpy>=1.16.4 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (1.23.5)
Requirement already satisfied: pandas>=0.24.2 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (2.1.1)
Requirement already satisfied: pdfminer.six>=20181108 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (20231228)
Requirement already satisfied: preshed>=2.0.1 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (3.0.9)
Requirement already satisfied: pycryptodome>=3.8.2 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (3.19.0)
Requirement already satisfied: pyrsistent>=0.15.2 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (0.19.3)
Requirement already satisfied: python-dateutil>=2.8.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (2.8.2)
Requirement already satisfied: pytz>=2019.1 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (2022.7.1)
Requirement already satisfied: requests>=2.22.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (2.29.0)
Requirement already satisfied: six>=1.12.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (1.16.0)
Requirement already satisfied: sortedcontainers>=2.1.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (2.4.0)
Requirement already satisfied: spacy>=2.1.4 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (3.7.4)
Requirement already satisfied: srsly>=0.0.7 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (1.0.7)
Requirement already satisfied: thinc>=7.0.4 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (8.2.3)
Requirement already satisfied: tqdm>=4.32.2 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (4.66.1)
Requirement already satisfied: urllib3>=1.25.3 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (1.26.17)
Requirement already satisfied: wasabi>=0.2.2 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pyresparser) (0.10.1)
Requirement already satisfied: click in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from nltk>=3.4.3->pyresparser) (8.1.7)
Requirement already satisfied: joblib in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from nltk>=3.4.3->pyresparser) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from nltk>=3.4.3->pyresparser) (2022.10.31)
Requirement already satisfied: tzdata>=2022.1 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pandas>=0.24.2->pyresparser) (2023.3)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pdfminer.six>=20181108->pyresparser) (3.3.0)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pdfminer.six>=20181108->pyresparser) (41.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from preshed>=2.0.1->pyresparser) (1.0.10)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from spacy>=2.1.4->pyresparser) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from spacy>=2.1.4->pyresparser) (1.0.5)
Collecting srsly>=0.0.7 (from pyresparser)
  Obtaining dependency information for srsly>=0.0.7 from https://files.pythonhosted.org/packages/0a/ed/d2c37221fe1975f4b6e8e3cf200d25b905b77e18f6a660b3dc149ade6192/srsly-2.4.8-cp310-cp310-win_amd64.whl.metadata
  Using cached srsly-2.4.8-cp310-cp310-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from spacy>=2.1.4->pyresparser) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from spacy>=2.1.4->pyresparser) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from spacy>=2.1.4->pyresparser) (0.9.0)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from spacy>=2.1.4->pyresparser) (6.4.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from spacy>=2.1.4->pyresparser) (1.10.9)
Requirement already satisfied: jinja2 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from spacy>=2.1.4->pyresparser) (3.1.2)
Requirement already satisfied: setuptools in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from spacy>=2.1.4->pyresparser) (68.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from spacy>=2.1.4->pyresparser) (20.9)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from spacy>=2.1.4->pyresparser) (3.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from thinc>=7.0.4->pyresparser) (0.1.4)
Requirement already satisfied: colorama in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from tqdm>=4.32.2->pyresparser) (0.4.6)
Requirement already satisfied: cffi>=1.12 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from cryptography>=36.0.0->pdfminer.six>=20181108->pyresparser) (1.15.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from packaging>=20.0->spacy>=2.1.4->pyresparser) (3.1.1)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=2.1.4->pyresparser) (4.7.1)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from weasel<0.4.0,>=0.1.0->spacy>=2.1.4->pyresparser) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from jinja2->spacy>=2.1.4->pyresparser) (2.1.3)
Requirement already satisfied: pycparser in c:\users\sheha\anaconda3\envs\adhd\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20181108->pyresparser) (2.21)
Using cached srsly-2.4.8-cp310-cp310-win_amd64.whl (481 kB)
Installing collected packages: srsly
  Attempting uninstall: srsly
    Found existing installation: srsly 1.0.7
    Uninstalling srsly-1.0.7:
      Successfully uninstalled srsly-1.0.7
Successfully installed srsly-2.4.8
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\sheha\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\sheha\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\sheha\appdata\roaming\python\python310\site-packages)
    WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\sheha\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\sheha\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\sheha\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\sheha\appdata\roaming\python\python310\site-packages)

In [1]:
import os
from pyresparser import ResumeParser

In [2]:
data = ResumeParser('Curriculum Vitae -Shehan Krishan.pdf').get_extracted_data()

c:\Users\sheha\anaconda3\envs\ADHD\lib\site-packages\spacy\util.py:275: UserWarning: [W031] Model 'en_training' (0.0.0) requires spaCy v2.1 and is incompatible with the current spaCy version (2.3.9). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

In [ ]:
data['skills']

In [ ]:
job_data={
    'Skills_Required': ['python', "machine" "learning", "data analysis"]
}
cv_db = {
    'shehan': 'Curriculum Vitae -Shehan Krishan.pdf', 
}

In [8]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

# Sample job vacancies data
job_vacancies = pd.DataFrame({
    'Job_Title': ['Data Scientist', 'Software Engineer', 'Web Developer', 'Machine Learning Engineer'],
    'Skills_Required': ['python, machine learning, data analysis', 'java, c++, software development', 'html, css, javascript, web development', 'machine learning, python, data engineering'],
    'Experience_Required': ['3 years', '2 years', '2 years', '4 years']
})

# Sample job seeker's skills and experience
job_seeker_skills = 'html, css, javascript'
job_seeker_experience = '2 years'

# Create a TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Combine skills and experience into one feature
job_vacancies['Features'] = job_vacancies['Skills_Required'] + ' ' + job_vacancies['Experience_Required']

# Fit and transform the TF-IDF vectorizer with the combined features
tfidf_matrix = tfidf_vectorizer.fit_transform(job_vacancies['Features'])

# Transform job seeker's skills and experience using the TF-IDF vectorizer
job_seeker_profile = tfidf_vectorizer.transform([job_seeker_skills + ' ' + job_seeker_experience])

# Calculate similarity scores
cosine_similarities = linear_kernel(job_seeker_profile, tfidf_matrix).flatten()

# Get job recommendations
job_vacancies['Similarity'] = cosine_similarities
recommended_jobs = job_vacancies.sort_values(by='Similarity', ascending=False).head(3)

print("Recommended Jobs:")
print(recommended_jobs[['Job_Title', 'Skills_Required', 'Experience_Required']])

Recommended Jobs:
           Job_Title                          Skills_Required  \
2      Web Developer   html, css, javascript, web development
1  Software Engineer          java, c++, software development
0     Data Scientist  python, machine learning, data analysis

  Experience_Required
2             2 years
1             2 years
0             3 years

In [7]:
job_vacancies

,Job_Title,Skills_Required,Experience_Required,Features,Similarity
0,Data Scientist,"python, machine learning, data analysis",3 years,"python, machine learning, data analysis 3 years",1.000000
1,Software Engineer,"java, c++, software development",2 years,"java, c++, software development 2 years",0.082569
2,Web Developer,"html, css, javascript, web development",2 years,"html, css, javascript, web development 2 years",0.063494
3,Machine Learning Engineer,"machine learning, python, data engineering",4 years,"machine learning, python, data engineering 4 y...",0.733950

In [27]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
import pickle

class JobRecommendationModel:
    def __init__(self):
        self.tfidf_vectorizer = TfidfVectorizer()
        self.tfidf_matrix = None
        self.job_vacancies = None

    def build_model(self, job_vacancies):
        self.job_vacancies = job_vacancies
        self._create_tfidf_matrix()

    def _create_tfidf_matrix(self):
        self.job_vacancies['Features'] = self.job_vacancies['Skills_Required']
        self.tfidf_matrix = self.tfidf_vectorizer.fit_transform(self.job_vacancies['Features'])

    def recommend_jobs(self, job_seeker_skills, job_seeker_experience, num_recommendations=3):
        job_seeker_profile = self.tfidf_vectorizer.transform([job_seeker_skills + ' ' + job_seeker_experience])
        cosine_similarities = linear_kernel(job_seeker_profile, self.tfidf_matrix).flatten()
        self.job_vacancies['score'] = cosine_similarities
        recommended_jobs = self.job_vacancies.sort_values(by='score', ascending=False).head(num_recommendations)
        return recommended_jobs[['Job_Title', 'Skills_Required', 'score']]

    def save_model(self, file_path):
        with open(file_path, 'wb') as file:
            pickle.dump(self, file)

    @classmethod
    def load_model(cls, file_path):
        with open(file_path, 'rb') as file:
            return pickle.load(file)

# Sample job vacancies data
job_vacancies = pd.DataFrame({
    'Job_Title': ['Data Scientist', 'Software Engineer', 'Web Developer', 'Machine Learning Engineer'],
    'Skills_Required': ['python, machine learning, data analysis', 'java, c++, software development', 'html, css, javascript, web development', 'machine learning, python, data engineering'],
})

# Create model and build it
model = JobRecommendationModel()
model.build_model(job_vacancies)

In [28]:
model.save_model("score.pkl")

In [29]:
loaded_model = JobRecommendationModel.load_model("score.pkl")

In [30]:
# Sample job seeker's skills and experience
job_seeker_skills = 'java, software development, database management'
job_seeker_experience = '3 years'

# Get recommendations
recommendations = loaded_model.recommend_jobs(job_seeker_skills, job_seeker_experience)
print("Recommended Jobs:")
print(recommendations)

Recommended Jobs:
           Job_Title                          Skills_Required  Similarity
1  Software Engineer          java, c++, software development    1.000000
2      Web Developer   html, css, javascript, web development    0.178578
0     Data Scientist  python, machine learning, data analysis    0.000000

# collaborative

In [19]:
import pandas as pd
import random

# Job Titles and their respective skills
job_titles = {
    "Software Engineer": ["java", "python", "c++", "software development", "algorithms"],
    "Web Developer": ["html", "css", "javascript", "web development", "frontend", "backend"],
    "Data Scientist": ["python", "r", "machine learning", "data analysis", "statistics"],
    "Database Administrator": ["sql", "database management", "data modeling", "oracle", "mysql"],
    "Network Engineer": ["networking", "ccna", "cisco", "routing", "switching"]
}

# Generating user data
user_data = {
    "ID": [],
    "Skills": [],
    "job_vacancies_Job_ID": [],
    "Job_Title": []
}

for i in range(50):
    user_id = random.randint(1, 20)
    job_id = random.choice([0, 1, 2, 3, 4])
    job_title = list(job_titles.keys())[job_id]
    skills = random.sample(job_titles[job_title], random.randint(1, len(job_titles[job_title])))
    user_data["ID"].append(user_id)
    user_data["Skills"].append(skills)
    user_data["job_vacancies_Job_ID"].append(job_id)
    user_data["Job_Title"].append(job_title)

user_df = pd.DataFrame(user_data)
print(user_df)

    ID                                             Skills  \
0    9               [networking, cisco, ccna, switching]
1    7  [data modeling, oracle, sql, database management]
2    3  [python, r, statistics, machine learning, data...
3    5    [software development, c++, algorithms, python]
4    7                                           [python]
5   12             [python, machine learning, statistics]
6    8                [python, statistics, data analysis]
7   10                                             [java]
8   16  [css, web development, html, javascript, backe...
9   20                                       [javascript]
10   1                               [algorithms, python]
11  18               [python, software development, java]
12  10                 [oracle, sql, database management]
13  18                                             [java]
14  14  [css, html, backend, javascript, web developme...
15  19      [frontend, html, javascript, web development]
16   4                                    [data modeling]
17  11                                             [java]
18   8               [java, software development, python]
19   5  [java, software development, algorithms, pytho...
20   6                        [networking, routing, ccna]
21  11                  [machine learning, statistics, r]
22  11  [css, html, web development, javascript, backe...
23   3    [python, c++, software development, algorithms]
24  12                 [ccna, networking, cisco, routing]
25  18               [ccna, cisco, networking, switching]
26  17                               [data modeling, sql]
27  16                              [database management]
28   8                         [sql, database management]
29  19      [ccna, networking, switching, routing, cisco]
30  20  [database management, mysql, sql, data modelin...
31  10                                    [data modeling]
32   4  [algorithms, software development, c++, python...
33   9  [javascript, html, css, backend, web development]
34   5            [algorithms, software development, c++]
35  13                                           [python]
36   4                       [java, software development]
37  11                                             [ccna]
38  12      [ccna, switching, cisco, networking, routing]
39  15                             [cisco, routing, ccna]
40  16    [software development, python, algorithms, c++]
41  15                                        [switching]
42   8                              [networking, routing]
43   4  [database management, sql, data modeling, oracle]
44  15                                           [oracle]
45  13  [web development, backend, javascript, css, fr...
46  17  [database management, sql, data modeling, mysq...
47  11                                              [c++]
48   9                                           [python]
49  12                     [switching, cisco, networking]

    job_vacancies_Job_ID               Job_Title
0                      4        Network Engineer
1                      3  Database Administrator
2                      2          Data Scientist
3                      0       Software Engineer
4                      0       Software Engineer
5                      2          Data Scientist
6                      2          Data Scientist
7                      0       Software Engineer
8                      1           Web Developer
9                      1           Web Developer
10                     0       Software Engineer
11                     0       Software Engineer
12                     3  Database Administrator
13                     0       Software Engineer
14                     1           Web Developer
15                     1           Web Developer
16                     3  Database Administrator
17                     0       Software Engineer
18                     0       Software Engineer
19                     0       Software Engineer
20                     4        Network Engineer
21                     2          Data Scientist
22                     1           Web Developer
23                     0       Software Engineer
24                     4        Network Engineer
25                     4        Network Engineer
26                     3  Database Administrator
27                     3  Database Administrator
28                     3  Database Administrator
29                     4        Network Engineer
30                     3  Database Administrator
31                     3  Database Administrator
32                     0       Software Engineer
33                     1           Web Developer
34                     0       Software Engineer
35                     2          Data Scientist
36                     0       Software Engineer
37                     4        Network Engineer
38                     4        Network Engineer
39                     4        Network Engineer
40                     0       Software Engineer
41                     4        Network Engineer
42                     4        Network Engineer
43                     3  Database Administrator
44                     3  Database Administrator
45                     1           Web Developer
46                     3  Database Administrator
47                     0       Software Engineer
48                     2          Data Scientist
49                     4        Network Engineer

In [20]:
unique_ids = user_df['ID'].unique()
print(unique_ids)

[ 9  7  3  5 12  8 10 16 20  1 18 14 19  4 11  6 17 13 15]

In [21]:
id_counts = user_df['ID'].value_counts()
print(id_counts)

ID
11    5
4     4
12    4
8     4
9     3
16    3
18    3
15    3
10    3
5     3
20    2
7     2
19    2
3     2
17    2
13    2
14    1
6     1
1     1
Name: count, dtype: int64

In [22]:
user_df

,ID,Skills,job_vacancies_Job_ID,Job_Title
0,9,"[networking, cisco, ccna, switching]",4,Network Engineer
1,7,"[data modeling, oracle, sql, database management]",3,Database Administrator
2,3,"[python, r, statistics, machine learning, data...",2,Data Scientist
3,5,"[software development, c++, algorithms, python]",0,Software Engineer
4,7,[python],0,Software Engineer
5,12,"[python, machine learning, statistics]",2,Data Scientist
6,8,"[python, statistics, data analysis]",2,Data Scientist
7,10,[java],0,Software Engineer
8,16,"[css, web development, html, javascript, backe...",1,Web Developer
9,20,[javascript],1,Web Developer
10,1,"[algorithms, python]",0,Software Engineer
11,18,"[python, software development, java]",0,Software Engineer
12,10,"[oracle, sql, database management]",3,Database Administrator
13,18,[java],0,Software Engineer
14,14,"[css, html, backend, javascript, web developme...",1,Web Developer
15,19,"[frontend, html, javascript, web development]",1,Web Developer
16,4,[data modeling],3,Database Administrator
17,11,[java],0,Software Engineer
18,8,"[java, software development, python]",0,Software Engineer
19,5,"[java, software development, algorithms, pytho...",0,Software Engineer
20,6,"[networking, routing, ccna]",4,Network Engineer
21,11,"[machine learning, statistics, r]",2,Data Scientist
22,11,"[css, html, web development, javascript, backe...",1,Web Developer
23,3,"[python, c++, software development, algorithms]",0,Software Engineer
24,12,"[ccna, networking, cisco, routing]",4,Network Engineer
25,18,"[ccna, cisco, networking, switching]",4,Network Engineer
26,17,"[data modeling, sql]",3,Database Administrator
27,16,[database management],3,Database Administrator
28,8,"[sql, database management]",3,Database Administrator
29,19,"[ccna, networking, switching, routing, cisco]",4,Network Engineer
30,20,"[database management, mysql, sql, data modelin...",3,Database Administrator
31,10,[data modeling],3,Database Administrator
32,4,"[algorithms, software development, c++, python...",0,Software Engineer
33,9,"[javascript, html, css, backend, web development]",1,Web Developer
34,5,"[algorithms, software development, c++]",0,Software Engineer
35,13,[python],2,Data Scientist
36,4,"[java, software development]",0,Software Engineer
37,11,[ccna],4,Network Engineer
38,12,"[ccna, switching, cisco, networking, routing]",4,Network Engineer
39,15,"[cisco, routing, ccna]",4,Network Engineer
40,16,"[software development, python, algorithms, c++]",0,Software Engineer
41,15,[switching],4,Network Engineer
42,8,"[networking, routing]",4,Network Engineer
43,4,"[database management, sql, data modeling, oracle]",3,Database Administrator
44,15,[oracle],3,Database Administrator
45,13,"[web development, backend, javascript, css, fr...",1,Web Developer
46,17,"[database management, sql, data modeling, mysq...",3,Database Administrator
47,11,[c++],0,Software Engineer
48,9,[python],2,Data Scientist
49,12,"[switching, cisco, networking]",4,Network Engineer

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# Convert list of skills to text
user_df['Skills_text'] = user_df['Skills'].apply(lambda x: ' '.join(x))

# Convert Job_Title to target
y = user_df['Job_Title']

# Convert Skills_text to features
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(user_df['Skills_text'])

# Train Naive Bayes classifier
clf = MultinomialNB()
clf.fit(X, y)

def recommend_job_title(skills):
    # Convert skills to text
    skills_text = ' '.join(skills)
    
    # Transform skills to features
    skills_features = vectorizer.transform([skills_text])
    
    # Predict job title
    predicted_title = clf.predict(skills_features)
    
    return predicted_title[0]

In [44]:
# Example usage
skills = ["machine learning"]
recommended_title = recommend_job_title(skills)
print("Recommended Job Title based on skills {}: {}".format(skills, recommended_title))

Recommended Job Title based on skills ['machine learning']: Data Scientist

In [48]:
user_df.to_csv("dataUser.csv")

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Convert list of skills to text
# user_df['Skills_text'] = user_df['Skills'].apply(lambda x: ' '.join(x))

# Convert Skills_text to features
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(user_df['Skills_text'])

def recommend_job_title_cosine_similarity(skills):
    # Convert skills to text
    skills_text = ' '.join(skills)

    # Transform skills to features
    skills_features = vectorizer.transform([skills_text])

    # Calculate cosine similarity between input skills and job skills
    cosine_similarities = cosine_similarity(skills_features, X)

    # Get indices of top similar job titles
    similar_jobs_indices = cosine_similarities.argsort()[0][::-1]

    # Get top 5 similar job titles
    top_similar_jobs = user_df.iloc[similar_jobs_indices[:5]]['Job_Title'].unique()

    return top_similar_jobs

# Example usage
skills = ["python", "data analysis", "machine learning"]
recommended_titles = recommend_job_title_cosine_similarity(skills)
print("Recommended Job Titles based on skills {} using Cosine Similarity: {}".format(skills, recommended_titles))

Recommended Job Titles based on skills ['python', 'data analysis', 'machine learning'] using Cosine Similarity: ['Data Scientist']

In [60]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Convert list of skills to text
user_df['Skills_text'] = user_df['Skills'].apply(lambda x: ' '.join(x))

# Convert Skills_text to features
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(user_df['Skills_text'])

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, user_df['Job_Title'], test_size=0.2, random_state=42)

# Train K-Nearest Neighbors classifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

def recommend_job_title_knn(skills):
    # Transform skills to features
    skills_features = vectorizer.transform([' '.join(skills)])

    # Predict job title
    predicted_title = knn.predict(skills_features)

    return predicted_title[0]

In [64]:
def recommend_job_title_knn_acc(skills):
    # Transform skills to features
    # skills_features = vectorizer.transform([' '.join(skills)])

    # Predict job title
    predicted_title = knn.predict(skills)

    return predicted_title[0]

In [65]:
y_pred = [recommend_job_title_knn_acc(skills) for skills in X_test]

In [66]:
accuracy = accuracy_score(y_test, y_pred)
print("Model: K-Nearest Neighbors, Accuracy: {:.2f}".format(accuracy))

Model: K-Nearest Neighbors, Accuracy: 0.90

In [63]:
# Example usage
skills = ["python", "data analysis", "machine learning"]
recommended_title = recommend_job_title_knn(skills)
print("Recommended Job Title based on skills {} using K-Nearest Neighbors: {}".format(skills, recommended_title))

Recommended Job Title based on skills ['python', 'data analysis', 'machine learning'] using K-Nearest Neighbors: Data Scientist

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


# Convert Skills_text to features
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(user_df['Skills_text'])

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, user_df['Job_Title'], test_size=0.2, random_state=42)

# Train Random Forest classifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

def recommend_job_title_rf(skills):
    # Transform skills to features
    skills_features = vectorizer.transform([' '.join(skills)])

    # Predict job title
    predicted_title = rf.predict(skills_features)

    return predicted_title[0]

def recommend_job_title_rf_acc(skills):
    # Predict job title
    predicted_title = rf.predict(skills)

    return predicted_title[0]

# Test the model
y_pred = [recommend_job_title_rf_acc(skills) for skills in X_test]
accuracy = accuracy_score(y_test, y_pred)
print("Model: Random Forest, Accuracy: {:.2f}".format(accuracy))

Model: Random Forest, Accuracy: 0.90

In [68]:
# Example usage
skills = ["python", "data analysis", "machine learning"]
recommended_title = recommend_job_title_rf(skills)
print("Recommended Job Title based on skills {} using Random Forest: {}".format(skills, recommended_title))

Recommended Job Title based on skills ['python', 'data analysis', 'machine learning'] using Random Forest: Data Scientist